apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./deployment/deployment.yaml
- ./deployment/namespace.yaml
- ./deployment/service-account.yaml
- ./ingress/ingress.yaml
- ./ingress/service.yaml

namespace: {{ cookiecutter._project_name_kebab_case }}