apiVersion: apps/v1
kind: Deployment
metadata:
  name:  app
  labels:
    app:  app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name:  app
        image:  {{ cookiecutter._project_name_lowercase_no_spaces }}:latest
        imagePullPolicy: IfNotPresent
        resources: 
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness 
            port: 8080
          initialDelaySeconds: 60 
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort:  8080
          name: app
      restartPolicy: Always
      terminationGracePeriodSeconds: 10