apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
- path: ingress-patch.yaml
  target:
    kind: Ingress
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: app